##Textfragmente
#untertitel: "Evaluationsbericht"
aktuelleStudienjahr: "HS21/FS22"
letztesStudienjahr: "HS20/FS21"
monat: "August"
jahr: "2023"
anzahlFixierteItems: "9"
#saison: "Winter"

##Plots
uebersichtAnzahlEvaluationen: "histogramms_0.pdf"
item1: "bars_0.pdf"
item2: "barsStudiengänge_0.pdf"
item3: "barsStudiengänge_1.pdf"
item4: "barsStudiengänge_2.pdf"
item5: "barsStudiengänge_3.pdf"
item6: "barsStudiengänge_4.pdf"
item7: "barsStudiengänge_5.pdf"
item8: "barsStudiengänge_6.pdf"
item9: "barsStudiengänge_7.pdf"

##Zu berechnende Werte
wert: ["VAR5", "VAR10"]

